AWSTemplateFormatVersion: '2010-09-09'
Description: 'Complete AWS infrastructure for postgis-property-search-demo-py with Ubuntu Bastion host'

Parameters:
  ProjectName:
    Type: String
    Default: 'postgis-property-search-demo-py'
    Description: 'Project name for resource naming'
  
  PostgreSQLVersion:
    Type: String
    Default: '15.4'
    Description: 'PostgreSQL engine version'
  
  DatabaseInstanceType:
    Type: String
    Default: 'db.r6g.large'
    Description: 'Database instance type'
  
  BastionInstanceType:
    Type: String
    Default: 't3.micro'
    Description: 'Bastion host instance type'
  
  KeyPairName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: 'EC2 Key Pair for SSH access to bastion host'

Resources:
  # VPC Configuration
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-vpc'

  # Internet Gateway
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-igw'

  InternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VPC

  # Public Subnets
  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [0, !GetAZs '']
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-public-1'

  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [1, !GetAZs '']
      CidrBlock: 10.0.2.0/24
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-public-2'

  # Private Subnets
  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [0, !GetAZs '']
      CidrBlock: 10.0.10.0/24
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-private-1'

  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [1, !GetAZs '']
      CidrBlock: 10.0.11.0/24
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-private-2'

  # Route Tables
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-public-rt'

  DefaultPublicRoute:
    Type: AWS::EC2::Route
    DependsOn: InternetGatewayAttachment
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  PublicSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref PublicSubnet1

  PublicSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref PublicSubnet2

  # Security Groups
  BastionSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub '${ProjectName}-bastion-sg'
      GroupDescription: Security group for bastion host
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 3000
          ToPort: 3000
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-bastion-sg'

  DatabaseSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub '${ProjectName}-db-sg'
      GroupDescription: Security group for database
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          SourceSecurityGroupId: !Ref BastionSecurityGroup
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-db-sg'

  # Database Subnet Group
  DatabaseSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group for database
      SubnetIds:
        - !Ref PrivateSubnet1
        - !Ref PrivateSubnet2
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-db-subnet-group'

  # Ubuntu Bastion Host
  BastionHost:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0c02fb55956c7d316  # Ubuntu 22.04 LTS (update for your region)
      InstanceType: !Ref BastionInstanceType
      KeyName: !Ref KeyPairName
      SubnetId: !Ref PublicSubnet1
      SecurityGroupIds:
        - !Ref BastionSecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          apt-get update
          apt-get install -y postgresql-client git curl python3 python3-pip nodejs npm
          
          # Install application dependencies (no PostgreSQL server installation)
          pip3 install psycopg2-binary boto3
          
          # Create demo script for RDS/Aurora connection
          cat > /home/ubuntu/connect_to_database.sh << 'EOF'
          #!/bin/bash
          # Connect to Aurora PostgreSQL with PostGIS
          echo "Connecting to Aurora PostgreSQL database..."
          DB_ENDPOINT="${DatabaseCluster.Endpoint}"
          psql postgresql://postgres:SecurePassword123!@$DB_ENDPOINT:5432/postgres
          EOF
          chmod +x /home/ubuntu/connect_to_database.sh
          chown ubuntu:ubuntu /home/ubuntu/connect_to_database.sh
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-bastion'

  # Aurora PostgreSQL Cluster
  DatabaseCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      DBClusterIdentifier: !Sub '${ProjectName}-aurora-cluster'
      Engine: aurora-postgresql
      EngineVersion: !Ref PostgreSQLVersion
      MasterUsername: postgres
      MasterUserPassword: SecurePassword123!
      VpcSecurityGroupIds:
        - !Ref DatabaseSecurityGroup
      DBSubnetGroupName: !Ref DatabaseSubnetGroup
      BackupRetentionPeriod: 7
      DeletionProtection: false
      StorageEncrypted: true
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-aurora-cluster'

  DatabaseInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: !Sub '${ProjectName}-aurora-instance'
      DBInstanceClass: !Ref DatabaseInstanceType
      Engine: aurora-postgresql
      DBClusterIdentifier: !Ref DatabaseCluster
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-aurora-instance'

Outputs:
  VPCId:
    Description: VPC ID
    Value: !Ref VPC

  BastionPublicIP:
    Description: Bastion host public IP
    Value: !GetAtt BastionHost.PublicIp

  DatabaseEndpoint:
    Description: Database endpoint
    Value: !GetAtt DatabaseCluster.Endpoint

  DatabasePort:
    Description: Database port
    Value: 5432

  SSHCommand:
    Description: SSH command to connect to bastion host
    Value: !Sub 'ssh -i your-key.pem ubuntu@${BastionHost.PublicIp}'

  DatabaseConnection:
    Description: Database connection string from bastion host
    Value: !Sub 'postgresql://postgres:SecurePassword123!@${DatabaseCluster.Endpoint}:5432/postgres'

  PostGISSetupCommand:
    Description: Command to enable PostGIS extension
    Value: 'psql -c "CREATE EXTENSION IF NOT EXISTS postgis;" <connection_string>'
